import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MetaMaskProvider } from "@metamask/sdk-react";
import { Providers } from "./providers";

const satoshi = localFont({
  src: "../assets/fonts/Satoshi Variable.ttf",
  variable: "--font-satoshi",
});
const playfair = localFont({
  src: "../assets/fonts/PlayfairDisplay VariableFont.ttf",
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${playfair.variable} font-sans antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
